package br.edu.infnet.AppOrderProduct;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import br.edu.infnet.AppOrderProduct.model.domain.Account;

@Component
public class AccountTest implements ApplicationRunner {

	@Override
	public void run(ApplicationArguments args) throws Exception {
		
		/* Data generated by https://www.4devs.com.br/gerador_de_pessoas */
		Account acc = new Account();
		acc.setName("Benjamin Antonio Caio Ribeiro");
		acc.setDocumentNumber("88696268814");
		acc.setEmail("benjaminantonioribeiro@piscinasegura.com.br");
		acc.setAddressCity("Campinas");
		acc.setAddressComplement("AP 404");
		acc.setAddressCountry("BRAZIL");
		acc.setAddressNumber("812");
		acc.setAddressPostalCode("13058-414");
		acc.setAddressState("SP");
		acc.setAddressStreet("Rua Maestro Armando Belardi");
		
		System.out.println("Account - "+acc);
		
	}

}
